language: ruby
rvm:
  - 2.6
env:
  secure: EQ01qZUxCuISMlJRoxJk+2gtdMcSbe3xw8qATb/F3Mi13MyYd52foju1zopWJGK8hvNZdJiGIvKylYNp6DIMqA6SBjeJWouOApWnuJ5p/6cSuWR9A7x2PKWc1gQmAiVyyReApOqR7gw/YPL07PM6RIfrTrrFwiMDyV4uWj1dCB9Irhj6HHRWoMRIqJFS/h43ZlxYDcZRk9F+3x26YRusNCjtbZctEKpLEhCZj+ixLPgAE8ZxOJxVMYaDFmHrZXNcpWOVU7KF+4TfmCY90c/U+5ukreJjO579bATh+z9rcqdnuuSK+HTwAmY7M7JKNbahLYkm1SSNyAxNuJanB3s2kS9KaSyIJxRo+0Mh1cAo3rpZ/yFi882fCmCbvbs6q/fHBA+giHzkoNWvz17mNkDnkpfcCIDa941BR6CPhQ/TWZ06wcTxy5i/S1Abu7gg2iVOnzrQwj+o+R+K5YApTYSNDwOybVcV9AEOxVVoNIDpiOqP6JjjdOqVUOAm4kCjZA5aFIzcLT8fPOH8xY4DG7sI5h/Ks1552JpXsG7rhpAA8LttEnz0CA7yovrs9IFhkhLBILY20sqL5ZUCFmG0qzz68XknIPskrvOepfZlTFFvTw74TrwfJadG7rjNitDfvSDUPp4oKR6ymWFu02ICOxDe6WRxft86x15qHki4aaOk41w=
before_script:
  - gem install awesome_bot
  - gem install danger
script:
  - wl=CONTRIBUTING,awesome-ha.com,twitter.com/frenck,github.com/frenck/awesome-home-assistant,discord.me
  - awesome_bot README.md --allow-redirect --white-list $wl
  - danger
notifications:
  email: false
