title: "I want to report something else"
body:
  - type: input
    attributes:
      label: Affected link
      placeholder: "https://"
      description: >-
        If this report is about one of the items listed on the Awesome list,
        please paste the actual link (and not the description).

  - type: textarea
    attributes:
      label: Wassup?
      description: >
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
