---
name: Awesome CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 12 * * *'

permissions:
  contents: read

jobs:
  lint:
    name: Awesome list lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run awesome-lint
        run: npx awesome-lint@2.3.0
