---
name: Awesome CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 12 * * *'

permissions:
  contents: read

jobs:
  lint:
    name: Awesome list lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run awesome-lint
        run: npx awesome-lint@2.3.0
