---
name: Labels

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
    paths:
      - .github/labels.yml
      - .github/workflows/labels.yaml
  pull_request:
    paths:
      - .github/labels.yml
      - .github/workflows/labels.yaml
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  sync:
    name: Sync labels with GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@548a7c3603594ec17c819e1239f281a3b801ab4d # v6.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false
          dry-run: ${{ github.event_name == 'pull_request' }}
