---
name: Zizmor

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/**
      - .github/zizmor.yml
  pull_request:
    paths:
      - .github/workflows/**
      - .github/zizmor.yml
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  zizmor:
    name: Zizmor workflow audit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3
        with:
          inputs: ./.github/workflows/
          advanced-security: true
